<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ratih extends Model
{
    //use HasFactory;
    protected $table = 'tih_ratih';
    protected $fillable = [
        'dt_chamado',
        'numero_chamado',
        'paciente_nome',
        'paciente_prontuario',
        'paciente_dt_nascimento',
        'paciente_sexo',
        'hipotese_diagnostico',
        'classificacao_risco',
        'fk_unidade_origem',
        'setor_origem',
        'fk_unidade_destino',
        'setor_destino',
        'tipo_viatura',
        'Justificativa_tipo_viatura',
        'fk_user_cancelamento_ratih',
        'Justificativa_cancelamento_viatura',
        'exame_imagem',
        'avaliacao',
        'transferencia_internacao',
        'outros',
        'outros_anotacao',
        'medico_solicitante_nome',
        'medico_solicitante_crm',
        'autorizacao_nome',
        'autorizacao_funcao',
        'autorizacao_matricula',
        'pa_origem',
        'x_origem',
        'fc_origem',
        'fr_origem',
        'spo2_origem',
        'glicemia_origem',
        'taxa_origem',
        'anotacoes_exame_fisico_origem',
        'ar_ambiente_origem',
        'coletor_nasal_origem',
        'coletor_nasal_anotacao_origem',
        'mascara_alto_fluxo_origem',
        'mascara_alto_fluxo_anotacao_origem',
        'esfoco_respiratorio_origem',
        'bomba_infusora_origem',
        'bomba_infusora_med_1_origem',
        'bomba_infusora_med_2_origem',
        'bomba_infusora_med_3_origem',
        'bomba_infusora_med_4_origem',
        'bomba_infusora_med_5_origem',
        'paciente_entubado_origem',
        'glasgow_AO_menor_origem',
        'glasgow_rv_menor_origem',
        'glasgow_rm_menor_origem',
        'glasgow_AO_maior_origem',
        'glasgow_rv_maior_origem',
        'glasgow_rm_maior_origem',
        'rass_1_origem',
        'rass_2_origem', 
        'autorizacao_transferencia_origem',
        'exame_procedimentos_origem',
        'ultima_evolucao_origem',
        'ultima_prescricao_origem',
        'teste_covid_origem',
        'documento_pessoal_paciente_origem',
        'exame_laboratorial_origem',
        'exame_imagem_origem',
        'bam_entrada_origem',
        'outro_doc_origem',
        'obs_gerais_origem',
        'pa_destino',
        'x_destino',
        'fc_destino',
        'fr_destino',
        'spo2_destino',
        'glicemia_destino',
        'taxa_destino',
        'anotacoes_exame_fisico_destino',
        'ar_ambiente_destino',
        'coletor_nasal_destino',
        'coletor_nasal_anotacao_destino',
        'mascara_alto_fluxo_destino',
        'mascara_alto_fluxo_anotacao_destino',
        'esfoco_respiratorio_destino',
        'bomba_infusora_destino',
        'bomba_infusora_med_1_destino',
        'bomba_infusora_med_2_destino',
        'bomba_infusora_med_3_destino',
        'bomba_infusora_med_4_destino',
        'bomba_infusora_med_5_destino',
        'glasgow_AO_menor_destino',
        'glasgow_rv_menor_destino',
        'glasgow_rm_menor_destino',
        'glasgow_AO_maior_destino',
        'glasgow_rv_maior_destino',
        'glasgow_rm_maior_destino',
        'rass_1_destino',
        'rass_2_destino',        
        'autorizacao_transferencia_destino',
        'exame_procedimentos_destino',
        'ultima_evolucao_destino',
        'ultima_prescricao_destino',
        'teste_covid_destino',
        'documento_pessoal_paciente_destino',
        'exame_laboratorial_destino',
        'exame_imagem_destino',
        'bam_entrada_destino',
        'outro_doc_destino',
        'obs_gerais_destino',
        'intercorrencia_destino',
        'intercorrencia_motivo_anotacao_destino',
        'fk_tih_equipe_viatura',
        'dt_rh_saida_base',
        'fk_user_rh_saida_base',
        'dt_rh_unidade_origem',
        'fk_user_rh_unidade_origem',
        'dt_rh_saida_unidade_origem',
        'fk_user_rh_saida_unidade_origem',
        'dt_rh_chegada_unidade_destino',
        'fk_user_rh_chegada_unidade_destino',
        'dt_rh_saida_unidade_destino',
        'fk_user_rh_saida_unidade_destino',
        'dt_rh_chegada_base',
        'fk_user_rh_chegada_base',     
    ];
    
    protected $hidden = [
        '_token',
     
    ];

    protected $casts = [
        'paciente_dt_nascimento' => 'date',
        'dt_chamado' => 'datetime',
        'dt_rh_saida_base' => 'datetime',
        'dt_rh_unidade_origem' => 'datetime',
        'dt_rh_saida_unidade_origem' => 'datetime',
        'dt_rh_chegada_unidade_destino' => 'datetime',
        'dt_rh_saida_unidade_destino' => 'datetime',
        'dt_rh_chegada_base' => 'datetime',

        
     ];

     public function equipeViatura()
    {
        return $this->belongsTo(EquipeViatura::class, 'fk_tih_equipe_viatura');
    }
}
